[features]
seeds = false
skip-lint = false
[programs.devnet]
nft_staking = "92Uesmw2wPEL9hHqTLmxSupCjKkr6nadWLUYKzjvQ8mg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/tuanpm/codingcamp/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
